### Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "sender": "u1",
  "title": "First post",
  "content": "Hello world"
}

### Get All Posts
GET http://localhost:3000/post

### Get Post By Id (replace id)
GET http://localhost:3000/post/{{postId}}

### Get Posts By Sender
GET http://localhost:3000/post?sender=u1

### Create Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postId": "{{postId}}",
  "sender": "u2",
  "message": "Nice post!"
}

### Get Comment By Id
GET http://localhost:3000/comment/{{commentId}}

### Update Comment
PUT http://localhost:3000/comment/{{commentId}}
Content-Type: application/json

{
  "sender": "u2",
  "message": "Edited comment"
}
